# Generated by Django 5.1.5 on 2025-01-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('bmi', models.FloatField()),
                ('glucose', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('insulin', models.FloatField()),
                ('diabetes_pedigree', models.FloatField()),
                ('pregnancies', models.IntegerField()),
                ('skin_thickness', models.FloatField()),
                ('prediction', models.BooleanField()),
                ('probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
